version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module1:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=FIREFOX
      - HUB_HOST=hub
      - XMLFILE=searchTestNG.xml
    volumes:
      - ./search-results1:/usr/share/udemy/test-output
  search-module2:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=CHROME
      - HUB_HOST=hub
      - XMLFILE=searchTestNG.xml
    volumes:
      - ./search-results2:/usr/share/udemy/test-output
  book-flight-module1:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
        - BROWSER=CHROME
        - HUB_HOST=hub
        - XMLFILE=flightTestNG.xml
    volumes:
        - ./flight-results1:/usr/share/udemy/test-output
  book-flight-module2:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
        - BROWSER=FIREFOX
        - HUB_HOST=hub
        - XMLFILE=flightTestNG.xml
    volumes:
        - ./flight-results2:/usr/share/udemy/test-output