version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=FIREFOX
      - HUB_HOST=hub
      - XMLFILE=searchTestNG.xml
    volumes:
      - ./output/search-results:/usr/share/udemy/test-output
  book-flight-module:
    image: anilcheepuru92/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
        - BROWSER=CHROME
        - HUB_HOST=hub
        - XMLFILE=flightTestNG.xml
    volumes:
        - ./output/flight-results:/usr/share/udemy/test-output